#!/bin/bash

# Copyright (c) 2021-2024, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Exit on error
set -e

# Check if project name was provided
if [ -z "$1" ]; then
    echo "Error: Project name not provided!"
    echo "Usage: $0 <project_name>"
    exit 1
fi

PROJECT_NAME=$1
CONFIG_FILE="nvflare_project_config_${PROJECT_NAME}.yml"

echo "Starting NVFlare provisioning process for project: ${PROJECT_NAME}"

# Check if main.py exists
if [ ! -f "project_builder.py" ]; then
    echo "Error: project_builder.py not found!"
    exit 1
fi

# Step 1: Run the Python preprocessing script with project name
echo "Running preprocessing script..."
python3 project_builder.py "${PROJECT_NAME}"

# Check if the Python script executed successfully
if [ $? -ne 0 ]; then
    echo "Error: Python preprocessing failed!"
    exit 1
fi

# Check if config file was generated successfully
if [ ! -f "${CONFIG_FILE}" ]; then
    echo "Error: ${CONFIG_FILE} was not generated by project_builder.py!"
    exit 1
fi

# Step 2: Run NVFlare provision command
echo "Running NVFlare provision..."
nvflare provision -p "${CONFIG_FILE}"

# Check if provision was successful
if [ $? -ne 0 ]; then
    echo "Error: NVFlare provision failed!"
    exit 1
fi

echo "NVFlare provisioning completed successfully for project: ${PROJECT_NAME}!"

# After nvflare provision completes successfully this script builds and configures the default setup to run nvflare
python3 preconfig_project_folders.py "${PROJECT_NAME}"
echo "Pre-configuration has been successful!"